version: "3.8"
services:
  dev-postgres:
    image: postgres:15.1-alpine
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PW}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data  # データの永続化
    restart: always
    networks:
      - lesson

volumes:
  postgres_data:  # 永続化用のボリュームを定義
    driver: local

networks:
  lesson: